export type VirtualTeacher = {
    id: string;
    name: string;
    email: string;
    role: string;
    status: string;
  };
  
  export const virtualTeachers: VirtualTeacher[] = [
    {
      id: "1",
      name: "John Doe",
      email: "john.doe@example.com",
      role: "admin",
      status: "active",
    },
    {
      id: "2",
      name: "Jane Doe",
      email: "jane.doe@example.com",
      role: "admin",
      status: "active",
    },
    {
      id: "3",
      name: "Robert Johnson",
      email: "robert.johnson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "4",
      name: "Emily Davis",
      email: "emily.davis@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "5",
      name: "Michael Wilson",
      email: "michael.wilson@example.com",
      role: "teacher",
      status: "inactive",
    },
    {
      id: "6",
      name: "Sarah Brown",
      email: "sarah.brown@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "7",
      name: "David Miller",
      email: "david.miller@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "8",
      name: "Jessica Taylor",
      email: "jessica.taylor@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "9",
      name: "Thomas Anderson",
      email: "thomas.anderson@example.com",
      role: "support",
      status: "active",
    },
    {
      id: "10",
      name: "Jennifer Martin",
      email: "jennifer.martin@example.com",
      role: "support",
      status: "active",
    },
    {
      id: "11",
      name: "Christopher Lee",
      email: "christopher.lee@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "12",
      name: "Amanda White",
      email: "amanda.white@example.com",
      role: "teacher",
      status: "inactive",
    },
    {
      id: "13",
      name: "Daniel Thompson",
      email: "daniel.thompson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "14",
      name: "Stephanie Garcia",
      email: "stephanie.garcia@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "15",
      name: "Brian Rodriguez",
      email: "brian.rodriguez@example.com",
      role: "admin",
      status: "active",
    },
    {
      id: "16",
      name: "Lisa Martinez",
      email: "lisa.martinez@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "17",
      name: "Mark Johnson",
      email: "mark.johnson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "18",
      name: "Michelle Williams",
      email: "michelle.williams@example.com",
      role: "teacher",
      status: "inactive",
    },
    {
      id: "19",
      name: "James Smith",
      email: "james.smith@example.com",
      role: "support",
      status: "active",
    },
    {
      id: "20",
      name: "Patricia Brown",
      email: "patricia.brown@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "21",
      name: "Richard Davis",
      email: "richard.davis@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "22",
      name: "Elizabeth Wilson",
      email: "elizabeth.wilson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "23",
      name: "Joseph Taylor",
      email: "joseph.taylor@example.com",
      role: "teacher",
      status: "inactive",
    },
    {
      id: "24",
      name: "Nancy Anderson",
      email: "nancy.anderson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "25",
      name: "Charles Martin",
      email: "charles.martin@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "26",
      name: "Karen Thompson",
      email: "karen.thompson@example.com",
      role: "admin",
      status: "active",
    },
    {
      id: "27",
      name: "Thomas White",
      email: "thomas.white@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "28",
      name: "Sarah Garcia",
      email: "sarah.garcia@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "29",
      name: "Daniel Rodriguez",
      email: "daniel.rodriguez@example.com",
      role: "support",
      status: "inactive",
    },
    {
      id: "30",
      name: "Jessica Martinez",
      email: "jessica.martinez@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "31",
      name: "William Johnson",
      email: "william.johnson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "32",
      name: "Barbara Williams",
      email: "barbara.williams@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "33",
      name: "David Smith",
      email: "david.smith@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "34",
      name: "Linda Brown",
      email: "linda.brown@example.com",
      role: "admin",
      status: "inactive",
    },
    {
      id: "35",
      name: "Michael Davis",
      email: "michael.davis@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "36",
      name: "Elizabeth Wilson",
      email: "elizabeth.wilson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "37",
      name: "Robert Taylor",
      email: "robert.taylor@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "38",
      name: "Jennifer Anderson",
      email: "jennifer.anderson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "39",
      name: "Joseph Martin",
      email: "joseph.martin@example.com",
      role: "support",
      status: "active",
    },
    {
      id: "40",
      name: "Maria Thompson",
      email: "maria.thompson@example.com",
      role: "teacher",
      status: "inactive",
    },
    {
      id: "41",
      name: "Charles White",
      email: "charles.white@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "42",
      name: "Susan Garcia",
      email: "susan.garcia@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "43",
      name: "Thomas Rodriguez",
      email: "thomas.rodriguez@example.com",
      role: "admin",
      status: "active",
    },
    {
      id: "44",
      name: "Margaret Martinez",
      email: "margaret.martinez@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "45",
      name: "Christopher Johnson",
      email: "christopher.johnson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "46",
      name: "Dorothy Williams",
      email: "dorothy.williams@example.com",
      role: "support",
      status: "inactive",
    },
    {
      id: "47",
      name: "Daniel Smith",
      email: "daniel.smith@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "48",
      name: "Lisa Brown",
      email: "lisa.brown@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "49",
      name: "Paul Davis",
      email: "paul.davis@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "50",
      name: "Nancy Wilson",
      email: "nancy.wilson@example.com",
      role: "admin",
      status: "active",
    },
    {
      id: "51",
      name: "Mark Taylor",
      email: "mark.taylor@example.com",
      role: "teacher",
      status: "inactive",
    },
    {
      id: "52",
      name: "Karen Anderson",
      email: "karen.anderson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "53",
      name: "Donald Martin",
      email: "donald.martin@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "54",
      name: "Sarah Thompson",
      email: "sarah.thompson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "55",
      name: "Richard White",
      email: "richard.white@example.com",
      role: "support",
      status: "active",
    },
    {
      id: "56",
      name: "Linda Garcia",
      email: "linda.garcia@example.com",
      role: "teacher",
      status: "inactive",
    },
    {
      id: "57",
      name: "William Rodriguez",
      email: "william.rodriguez@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "58",
      name: "Elizabeth Martinez",
      email: "elizabeth.martinez@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "59",
      name: "David Johnson",
      email: "david.johnson@example.com",
      role: "admin",
      status: "active",
    },
    {
      id: "60",
      name: "Barbara Williams",
      email: "barbara.williams@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "61",
      name: "Michael Smith",
      email: "michael.smith@example.com",
      role: "teacher",
      status: "inactive",
    },
    {
      id: "62",
      name: "Jennifer Brown",
      email: "jennifer.brown@example.com",
      role: "support",
      status: "active",
    },
    {
      id: "63",
      name: "Robert Davis",
      email: "robert.davis@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "64",
      name: "Maria Wilson",
      email: "maria.wilson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "65",
      name: "Charles Taylor",
      email: "charles.taylor@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "66",
      name: "Susan Anderson",
      email: "susan.anderson@example.com",
      role: "admin",
      status: "inactive",
    },
    {
      id: "67",
      name: "Joseph Martin",
      email: "joseph.martin@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "68",
      name: "Margaret Thompson",
      email: "margaret.thompson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "69",
      name: "Thomas White",
      email: "thomas.white@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "70",
      name: "Dorothy Garcia",
      email: "dorothy.garcia@example.com",
      role: "support",
      status: "active",
    },
    {
      id: "71",
      name: "Christopher Rodriguez",
      email: "christopher.rodriguez@example.com",
      role: "teacher",
      status: "inactive",
    },
    {
      id: "72",
      name: "Lisa Martinez",
      email: "lisa.martinez@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "73",
      name: "Daniel Johnson",
      email: "daniel.johnson@example.com",
      role: "admin",
      status: "active",
    },
    {
      id: "74",
      name: "Nancy Williams",
      email: "nancy.williams@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "75",
      name: "Paul Smith",
      email: "paul.smith@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "76",
      name: "Karen Brown",
      email: "karen.brown@example.com",
      role: "teacher",
      status: "inactive",
    },
    {
      id: "77",
      name: "Mark Davis",
      email: "mark.davis@example.com",
      role: "support",
      status: "active",
    },
    {
      id: "78",
      name: "Linda Wilson",
      email: "linda.wilson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "79",
      name: "Donald Taylor",
      email: "donald.taylor@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "80",
      name: "Sarah Anderson",
      email: "sarah.anderson@example.com",
      role: "admin",
      status: "active",
    },
    {
      id: "81",
      name: "Richard Martin",
      email: "richard.martin@example.com",
      role: "teacher",
      status: "inactive",
    },
    {
      id: "82",
      name: "Barbara Thompson",
      email: "barbara.thompson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "83",
      name: "William White",
      email: "william.white@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "84",
      name: "Elizabeth Garcia",
      email: "elizabeth.garcia@example.com",
      role: "support",
      status: "active",
    },
    {
      id: "85",
      name: "David Rodriguez",
      email: "david.rodriguez@example.com",
      role: "teacher",
      status: "inactive",
    },
    {
      id: "86",
      name: "Jennifer Martinez",
      email: "jennifer.martinez@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "87",
      name: "Michael Johnson",
      email: "michael.johnson@example.com",
      role: "admin",
      status: "active",
    },
    {
      id: "88",
      name: "Maria Williams",
      email: "maria.williams@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "89",
      name: "Robert Smith",
      email: "robert.smith@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "90",
      name: "Susan Brown",
      email: "susan.brown@example.com",
      role: "teacher",
      status: "inactive",
    },
    {
      id: "91",
      name: "Charles Davis",
      email: "charles.davis@example.com",
      role: "support",
      status: "active",
    },
    {
      id: "92",
      name: "Margaret Wilson",
      email: "margaret.wilson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "93",
      name: "Joseph Taylor",
      email: "joseph.taylor@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "94",
      name: "Dorothy Anderson",
      email: "dorothy.anderson@example.com",
      role: "admin",
      status: "active",
    },
    {
      id: "95",
      name: "Thomas Martin",
      email: "thomas.martin@example.com",
      role: "teacher",
      status: "inactive",
    },
    {
      id: "96",
      name: "Nancy Thompson",
      email: "nancy.thompson@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "97",
      name: "Daniel White",
      email: "daniel.white@example.com",
      role: "teacher",
      status: "active",
    },
    {
      id: "98",
      name: "Karen Garcia",
      email: "karen.garcia@example.com",
      role: "support",
      status: "active",
    },
    {
      id: "99",
      name: "Paul Rodriguez",
      email: "paul.rodriguez@example.com",
      role: "teacher",
      status: "inactive",
    },
    {
      id: "100",
      name: "Linda Martinez",
      email: "linda.martinez@example.com",
      role: "admin",
      status: "active",
    },
  ];